name: Notify user of closed issue

on:
  issues:
    types: [ closed ]

jobs:
  comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create comment (bug)
        if: contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, 'wontfix') == false
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Your issue has been closed. This likely means that we have implemented a fix. It is possible that it takes a while before you notice any changes. This is due to the fact that we first internally test the implementation. So please be patient if you do not notice any change immediately. 
            
            Thank you for understanding.
      - name: Create comment (feature)
        if: contains(github.event.issue.labels.*.name, 'feature') && contains(github.event.issue.labels.*.name, 'wontfix') == false
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Your feature request has been closed. This likely means that we have implemented your suggestion. It is possible that it takes a while before you notice any changes. This is due to the fact that we first internally test the implementation. So please be patient if you do not notice any change immediately. 
            
            Thank you for understanding.
